# Generated by Django 3.2.7 on 2021-09-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plot',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='description',
        ),
        migrations.AddField(
            model_name='plot',
            name='size',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
