# Generated by Django 3.2.7 on 2021-09-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210917_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
