# Generated by Django 3.2.7 on 2021-09-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_plot_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='size',
        ),
    ]
